test:
  adapter: sqlite3
  encoding: utf8
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

  development:
  	adapter: sqlite3
  	encoding: utf8
  	database: db/development.db
  	pool: 5
  	timeout: 5000